services:
  - type: web
    name: rhp-backend
    env: docker
    region: ohio
    plan: free
    healthCheckPath: /api/health
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: DIRECT_URL
        sync: false
      - key: PORT
        sync: false
      - key: GITHUB_TOKEN
        sync: false