services:
  - type: web
    name: rhp-backend
    env: docker
    region: ohio
    plan: free
    healthCheckPath: /api/health
    healthCheckTimeout: 600
    startCommand: pnpm run start:prod
    initialDeployHook: npx prisma generate
    dockerCommand: pnpm run start:prod
    scaling:
      minInstances: 1
      maxInstances: 1
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: DIRECT_URL
        sync: false
      - key: PORT
        value: 3000
      - key: NODE_ENV
        value: production
      - key: GITHUB_TOKEN
        sync: false
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false